version: '3'

services:
  mongo:
    container_name: mongo-container
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    volumes:
      - ./dist:/usr/src/app/dist
      - ./package.json:/usr/src/app/package.json
    ports:
      - 5050:5050
      - 9222:9222
    links:
      - mongo